name: rtd39
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - openbabel=3.1.1
  - mock
  - pillow
  - sphinx==3.4.3
  - sphinx_rtd_theme
  - pip>=20.1  # pip is needed as dependency
  - pandoc
  - pip:
    - keras>=3.0.0
    - tf-nightly-cpu==2.16.0.dev20231103  # Only need tensorflow for docs
    - jinja2==3.0.3
    - numpy
    - scipy
    - matplotlib
    - pandas
    - scikit-learn
    - pyyaml
    - rdkit  # Or via channels rdkit and conda rdkit
    - pymatgen
    - pyxtal
    - ase
    - ipython
    - nbsphinx
    - click
    - pyxtal